# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_approx_cpp <- function(x, table, nomatch, tolerance) {
    .Call('_Spectra_match_approx_cpp', PACKAGE = 'Spectra', x, table, nomatch, tolerance)
}

